In [4]:
from PIL import Image
from patchify import patchify, unpatchify
import numpy as np
from numpy import asarray

In [5]:
img_str = '/Users/nehawarikoo/Documents/atom-image-m-2-1024x1024-1.jpeg'

In [29]:
img = Image.open(img_str)
print(type(img))
numpydata = asarray(img)
print(numpydata.shape)
patches = patchify(numpydata, (1,1,3), step=1)
print(patches.shape)
print(patches[500][500][0])

<class 'PIL.JpegImagePlugin.JpegImageFile'>
(1024, 1024, 3)
(1024, 1024, 1, 1, 1, 3)
[[[249 147   3]]]


In [21]:
#Image.fromarray(patches[1000][500][0]).show()
f = '/Users/nehawarikoo/Downloads/Extractor/'
for i in range(0,len(patches)):
    for j in range(0, patches[i].shape[0]):
        Image.fromarray(patches[i][j][0]).save(f+str(i)+str(j)+'.jpg')

In [25]:
image = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
patches = patchify(image, (2,2), step=1)
print(patches)
print(patches.shape)

[[[[ 1  2]
   [ 5  6]]

  [[ 2  3]
   [ 6  7]]

  [[ 3  4]
   [ 7  8]]]


 [[[ 5  6]
   [ 9 10]]

  [[ 6  7]
   [10 11]]

  [[ 7  8]
   [11 12]]]]
(2, 3, 2, 2)
